// Base de données de démonstration réaliste pour EduGestion Africa
// Établissement : École Internationale du Sénégal (EIS Dakar)

import { 
  School, Student, Parent, Teacher, Classroom, Subject, 
  StudentFee, PaymentRecord, GradeEntry, ReportCard, 
  AttendanceRecord, TimetableSlot, HomeworkItem, NotificationItem, SuperAdminStats,
  PromotionRecord
} from '@/types';

export const DEMO_SCHOOL: School = {
  id: 'school-sn-001',
  name: 'École Internationale du Sénégal',
  code: 'EIS-DAKAR',
  slug: 'eis-dakar',
  logo: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=200&auto=format&fit=crop&q=80',
  slogan: 'L\'Excellence et la Rigueur au Service de la Jeunesse Africaine',
  address: 'Route des Almadies, Enclos 4B, Dakar',
  city: 'Dakar',
  country: 'Sénégal',
  phone: '+221 33 820 45 90',
  email: 'contact@eis-dakar.sn',
  website: 'https://eis-dakar.sn',
  academicLevels: ['Préscolaire', 'Élémentaire', 'Moyen (Collège)', 'Secondaire (Lycée)'],
  currency: 'FCFA',
  timezone: 'Africa/Dakar',
  createdAt: '2022-09-01',
  totalStudents: 842,
  totalTeachers: 54,
  totalClasses: 24,
};

export const DEMO_SUPER_ADMIN_STATS: SuperAdminStats = {
  totalSchools: 48,
  totalStudents: 18450,
  totalTeachers: 1240,
  activeSubscriptions: 42,
  trialSubscriptions: 5,
  expiredSubscriptions: 1,
  mrrFCFA: 2450000,
  arrFCFA: 29400000,
  monthlyGrowthPercent: 18.5,
  totalPaymentsVolumeFCFA: 482500000,
};

export const DEMO_CLASSES: Classroom[] = [
  { id: 'c-6a', name: '6ème A', level: '6e', cycle: 'COLLEGE', capacity: 35, studentCount: 32, roomNumber: 'Salle 101', mainTeacherId: 't-1', mainTeacherName: 'M. Ibrahima Diallo', academicYear: '2024-2025', averageGrade: 13.8 },
  { id: 'c-6b', name: '6ème B', level: '6e', cycle: 'COLLEGE', capacity: 35, studentCount: 34, roomNumber: 'Salle 102', mainTeacherId: 't-2', mainTeacherName: 'Mme Fatou Bintou Sow', academicYear: '2024-2025', averageGrade: 12.9 },
  { id: 'c-5a', name: '5ème A', level: '5e', cycle: 'COLLEGE', capacity: 35, studentCount: 30, roomNumber: 'Salle 103', mainTeacherId: 't-3', mainTeacherName: 'M. Cheikh Tidiane Sy', academicYear: '2024-2025', averageGrade: 14.1 },
  { id: 'c-4a', name: '4ème A', level: '4e', cycle: 'COLLEGE', capacity: 35, studentCount: 31, roomNumber: 'Salle 104', mainTeacherId: 't-4', mainTeacherName: 'Mme Mariama Ba', academicYear: '2024-2025', averageGrade: 13.4 },
  { id: 'c-3a', name: '3ème A', level: '3e', cycle: 'COLLEGE', capacity: 35, studentCount: 29, roomNumber: 'Salle 105', mainTeacherId: 't-1', mainTeacherName: 'M. Ibrahima Diallo', academicYear: '2024-2025', averageGrade: 14.7 },
  { id: 'c-2s', name: '2nde S', level: 'Seconde', cycle: 'LYCEE', capacity: 35, studentCount: 33, roomNumber: 'Salle 201', mainTeacherId: 't-5', mainTeacherName: 'M. Ousmane Sembène', academicYear: '2024-2025', averageGrade: 12.8 },
  { id: 'c-1s1', name: '1ère S1', level: 'Première', cycle: 'LYCEE', capacity: 30, studentCount: 26, roomNumber: 'Salle 202', mainTeacherId: 't-3', mainTeacherName: 'M. Cheikh Tidiane Sy', academicYear: '2024-2025', averageGrade: 15.2 },
  { id: 'c-ts2', name: 'Terminale S2', level: 'Terminale', cycle: 'LYCEE', capacity: 32, studentCount: 28, roomNumber: 'Salle 203', mainTeacherId: 't-5', mainTeacherName: 'M. Ousmane Sembène', academicYear: '2024-2025', averageGrade: 14.3 },
  { id: 'c-tl2', name: 'Terminale L2', level: 'Terminale', cycle: 'LYCEE', capacity: 32, studentCount: 27, roomNumber: 'Salle 204', mainTeacherId: 't-2', mainTeacherName: 'Mme Fatou Bintou Sow', academicYear: '2024-2025', averageGrade: 13.5 },
  { id: 'c-cm2', name: 'CM2 A', level: 'CM2', cycle: 'PRIMAIRE', capacity: 30, studentCount: 28, roomNumber: 'Salle P06', mainTeacherId: 't-6', mainTeacherName: 'Mme Aminata Traoré', academicYear: '2024-2025', averageGrade: 15.6 },
];

export const DEMO_SUBJECTS: Subject[] = [
  { id: 's-math', name: 'Mathématiques', code: 'MATH', defaultCoeff: 4.0, colorCode: '#2563EB' },
  { id: 's-fr', name: 'Français & Littérature', code: 'FR', defaultCoeff: 4.0, colorCode: '#DC2626' },
  { id: 's-pc', name: 'Physique - Chimie', code: 'PC', defaultCoeff: 3.0, colorCode: '#7C3AED' },
  { id: 's-svt', name: 'Sciences de la Vie et de la Terre', code: 'SVT', defaultCoeff: 2.0, colorCode: '#059669' },
  { id: 's-ang', name: 'Anglais', code: 'ANG', defaultCoeff: 2.0, colorCode: '#D97706' },
  { id: 's-hg', name: 'Histoire - Géographie', code: 'HG', defaultCoeff: 2.0, colorCode: '#EA580C' },
  { id: 's-philo', name: 'Philosophie', code: 'PHILO', defaultCoeff: 3.0, colorCode: '#4F46E5' },
  { id: 's-eps', name: 'Éducation Physique et Sportive', code: 'EPS', defaultCoeff: 1.0, colorCode: '#0891B2' },
  { id: 's-info', name: 'Informatique & Numérique', code: 'INFO', defaultCoeff: 1.5, colorCode: '#0284C7' },
];

export const DEMO_TEACHERS: Teacher[] = [
  {
    id: 't-1',
    matricule: 'PRF-2024-0001',
    firstName: 'Ibrahima',
    lastName: 'Diallo',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+221 77 654 32 10',
    email: 'i.diallo@eis-dakar.sn',
    specialty: 'Mathématiques',
    contractType: 'CDI',
    hireDate: '2019-10-01',
    isMainTeacherOf: '3ème A',
    assignedClasses: [
      { classId: 'c-3a', className: '3ème A', subjectId: 's-math', subjectName: 'Mathématiques' },
      { classId: 'c-6a', className: '6ème A', subjectId: 's-math', subjectName: 'Mathématiques' },
    ],
  },
  {
    id: 't-2',
    matricule: 'PRF-2024-0002',
    firstName: 'Fatou Bintou',
    lastName: 'Sow',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    phone: '+221 78 123 45 67',
    email: 'fb.sow@eis-dakar.sn',
    specialty: 'Français',
    contractType: 'CDI',
    hireDate: '2020-09-15',
    isMainTeacherOf: '6ème B',
    assignedClasses: [
      { classId: 'c-6b', className: '6ème B', subjectId: 's-fr', subjectName: 'Français' },
      { classId: 'c-tl2', className: 'Terminale L2', subjectId: 's-fr', subjectName: 'Français & Littérature' },
    ],
  },
  {
    id: 't-3',
    matricule: 'PRF-2024-0003',
    firstName: 'Cheikh Tidiane',
    lastName: 'Sy',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '+221 70 987 65 43',
    email: 'ct.sy@eis-dakar.sn',
    specialty: 'Physique - Chimie',
    contractType: 'CDI',
    hireDate: '2018-09-01',
    isMainTeacherOf: '1ère S1',
    assignedClasses: [
      { classId: 'c-1s1', className: '1ère S1', subjectId: 's-pc', subjectName: 'Physique - Chimie' },
      { classId: 'c-ts2', className: 'Terminale S2', subjectId: 's-pc', subjectName: 'Physique - Chimie' },
      { classId: 'c-3a', className: '3ème A', subjectId: 's-pc', subjectName: 'Physique - Chimie' },
    ],
  },
  {
    id: 't-4',
    matricule: 'PRF-2024-0004',
    firstName: 'Mariama',
    lastName: 'Ba',
    photo: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
    phone: '+221 76 543 21 09',
    email: 'm.ba@eis-dakar.sn',
    specialty: 'Anglais',
    contractType: 'CDI',
    hireDate: '2021-10-01',
    isMainTeacherOf: '4ème A',
    assignedClasses: [
      { classId: 'c-4a', className: '4ème A', subjectId: 's-ang', subjectName: 'Anglais' },
      { classId: 'c-3a', className: '3ème A', subjectId: 's-ang', subjectName: 'Anglais' },
      { classId: 'c-ts2', className: 'Terminale S2', subjectId: 's-ang', subjectName: 'Anglais' },
    ],
  },
  {
    id: 't-5',
    matricule: 'PRF-2024-0005',
    firstName: 'Ousmane',
    lastName: 'Sembène',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    phone: '+221 77 345 67 89',
    email: 'o.sembene@eis-dakar.sn',
    specialty: 'Sciences de la Vie et de la Terre',
    contractType: 'CDI',
    hireDate: '2017-09-01',
    isMainTeacherOf: 'Terminale S2',
    assignedClasses: [
      { classId: 'c-ts2', className: 'Terminale S2', subjectId: 's-svt', subjectName: 'SVT' },
      { classId: 'c-2s', className: '2nde S', subjectId: 's-svt', subjectName: 'SVT' },
    ],
  },
  {
    id: 't-6',
    matricule: 'PRF-2024-0006',
    firstName: 'Aminata',
    lastName: 'Traoré',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    phone: '+221 77 888 99 00',
    email: 'a.traore@eis-dakar.sn',
    specialty: 'Professeur d\'École Primaire',
    contractType: 'CDI',
    hireDate: '2020-09-01',
    isMainTeacherOf: 'CM2 A',
    assignedClasses: [
      { classId: 'c-cm2', className: 'CM2 A', subjectId: 's-fr', subjectName: 'Français' },
      { classId: 'c-cm2', className: 'CM2 A', subjectId: 's-math', subjectName: 'Mathématiques' },
    ],
  }
];

export const DEMO_PARENTS: Parent[] = [
  {
    id: 'p-1',
    firstName: 'Mamadou',
    lastName: 'Diop',
    phone: '+221 77 555 12 34',
    whatsapp: '+221 77 555 12 34',
    email: 'mamadou.diop@orange-sonatel.sn',
    profession: 'Cadre Supérieur Télécoms',
    address: 'Mermoz Pyrotechnie, Dakar',
    children: [
      { id: 'stu-1', matricule: 'EIS-2024-0012', name: 'Awa Diop', className: '3ème A', photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80', feeBalance: 100000, averageGrade: 16.4 },
      { id: 'stu-2', matricule: 'EIS-2024-0013', name: 'Moussa Diop', className: '6ème A', photo: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80', feeBalance: 50000, averageGrade: 14.8 },
      { id: 'stu-3', matricule: 'EIS-2024-0014', name: 'Fatou Diop', className: 'CM2 A', photo: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80', feeBalance: 0, averageGrade: 17.2 },
    ]
  },
  {
    id: 'p-2',
    firstName: 'Abdoulaye',
    lastName: 'Ndiaye',
    phone: '+221 78 444 88 99',
    whatsapp: '+221 78 444 88 99',
    email: 'a.ndiaye@portdakar.sn',
    profession: 'Ingénieur Maritime',
    address: 'Almadies, Zone 7, Dakar',
    children: [
      { id: 'stu-4', matricule: 'EIS-2024-0045', name: 'Cheikh Ndiaye', className: 'Terminale S2', photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80', feeBalance: 150000, averageGrade: 15.5 },
      { id: 'stu-5', matricule: 'EIS-2024-0046', name: 'Seynabou Ndiaye', className: '4ème A', photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80', feeBalance: 0, averageGrade: 13.9 },
    ]
  },
  {
    id: 'p-3',
    firstName: 'Khadija',
    lastName: 'Fall',
    phone: '+221 76 333 22 11',
    whatsapp: '+221 76 333 22 11',
    email: 'k.fall@avocats-dakar.com',
    profession: 'Avocate au Barreau',
    address: 'Fann Résidence, Dakar',
    children: [
      { id: 'stu-6', matricule: 'EIS-2024-0089', name: 'Babacar Fall', className: '1ère S1', photo: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80', feeBalance: 0, averageGrade: 16.8 },
    ]
  },
  {
    id: 'p-4',
    firstName: 'Moustapha',
    lastName: 'Sarr',
    phone: '+221 77 222 66 55',
    whatsapp: '+221 77 222 66 55',
    email: 'm.sarr@ecobank.sn',
    profession: 'Directeur d\'Agence Bancaire',
    address: 'Sacré-Cœur 3, Dakar',
    children: [
      { id: 'stu-7', matricule: 'EIS-2024-0102', name: 'Aïssatou Sarr', className: '3ème A', photo: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=150&auto=format&fit=crop&q=80', feeBalance: 200000, averageGrade: 11.2 },
    ]
  }
];

export const DEMO_STUDENTS: Student[] = [
  {
    id: 'stu-1',
    matricule: 'EIS-2024-0012',
    firstName: 'Awa',
    lastName: 'Diop',
    gender: 'FEMALE',
    birthDate: '2009-04-14',
    birthPlace: 'Dakar',
    nationality: 'Sénégalaise',
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    address: 'Mermoz Pyrotechnie, Dakar',
    bloodGroup: 'O+',
    medicalNotes: 'Aucune allergie connue.',
    classId: 'c-3a',
    className: '3ème A',
    level: '3e',
    academicYear: '2024-2025',
    status: 'INSCRIT',
    parentId: 'p-1',
    parentName: 'Mamadou Diop',
    parentPhone: '+221 77 555 12 34',
    parentWhatsapp: '+221 77 555 12 34',
    relationship: 'Père',
    totalFees: 350000,
    paidFees: 250000,
    feeBalance: 100000,
    averageGrade: 16.4,
    unjustifiedAbsences: 0,
  },
  {
    id: 'stu-2',
    matricule: 'EIS-2024-0013',
    firstName: 'Moussa',
    lastName: 'Diop',
    gender: 'MALE',
    birthDate: '2012-08-22',
    birthPlace: 'Dakar',
    nationality: 'Sénégalaise',
    photo: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    address: 'Mermoz Pyrotechnie, Dakar',
    bloodGroup: 'A+',
    medicalNotes: 'Asthme léger, inhalateur à disposition.',
    classId: 'c-6a',
    className: '6ème A',
    level: '6e',
    academicYear: '2024-2025',
    status: 'INSCRIT',
    parentId: 'p-1',
    parentName: 'Mamadou Diop',
    parentPhone: '+221 77 555 12 34',
    parentWhatsapp: '+221 77 555 12 34',
    relationship: 'Père',
    totalFees: 320000,
    paidFees: 270000,
    feeBalance: 50000,
    averageGrade: 14.8,
    unjustifiedAbsences: 1,
  },
  {
    id: 'stu-3',
    matricule: 'EIS-2024-0014',
    firstName: 'Fatou',
    lastName: 'Diop',
    gender: 'FEMALE',
    birthDate: '2014-01-10',
    birthPlace: 'Dakar',
    nationality: 'Sénégalaise',
    photo: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    address: 'Mermoz Pyrotechnie, Dakar',
    bloodGroup: 'O+',
    medicalNotes: 'R.A.S',
    classId: 'c-cm2',
    className: 'CM2 A',
    level: 'CM2',
    academicYear: '2024-2025',
    status: 'INSCRIT',
    parentId: 'p-1',
    parentName: 'Mamadou Diop',
    parentPhone: '+221 77 555 12 34',
    parentWhatsapp: '+221 77 555 12 34',
    relationship: 'Père',
    totalFees: 280000,
    paidFees: 280000,
    feeBalance: 0,
    averageGrade: 17.2,
    unjustifiedAbsences: 0,
  },
  {
    id: 'stu-4',
    matricule: 'EIS-2024-0045',
    firstName: 'Cheikh',
    lastName: 'Ndiaye',
    gender: 'MALE',
    birthDate: '2007-06-18',
    birthPlace: 'Saint-Louis',
    nationality: 'Sénégalaise',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    address: 'Almadies, Zone 7, Dakar',
    bloodGroup: 'B+',
    medicalNotes: 'Port de lunettes.',
    classId: 'c-ts2',
    className: 'Terminale S2',
    level: 'Terminale',
    academicYear: '2024-2025',
    status: 'INSCRIT',
    parentId: 'p-2',
    parentName: 'Abdoulaye Ndiaye',
    parentPhone: '+221 78 444 88 99',
    parentWhatsapp: '+221 78 444 88 99',
    relationship: 'Père',
    totalFees: 450000,
    paidFees: 300000,
    feeBalance: 150000,
    averageGrade: 15.5,
    unjustifiedAbsences: 2,
  },
  {
    id: 'stu-5',
    matricule: 'EIS-2024-0046',
    firstName: 'Seynabou',
    lastName: 'Ndiaye',
    gender: 'FEMALE',
    birthDate: '2010-11-05',
    birthPlace: 'Dakar',
    nationality: 'Sénégalaise',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    address: 'Almadies, Zone 7, Dakar',
    bloodGroup: 'O+',
    medicalNotes: 'R.A.S',
    classId: 'c-4a',
    className: '4ème A',
    level: '4e',
    academicYear: '2024-2025',
    status: 'INSCRIT',
    parentId: 'p-2',
    parentName: 'Abdoulaye Ndiaye',
    parentPhone: '+221 78 444 88 99',
    parentWhatsapp: '+221 78 444 88 99',
    relationship: 'Père',
    totalFees: 340000,
    paidFees: 340000,
    feeBalance: 0,
    averageGrade: 13.9,
    unjustifiedAbsences: 0,
  },
  {
    id: 'stu-6',
    matricule: 'EIS-2024-0089',
    firstName: 'Babacar',
    lastName: 'Fall',
    gender: 'MALE',
    birthDate: '2008-03-12',
    birthPlace: 'Thiès',
    nationality: 'Sénégalaise',
    photo: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
    address: 'Fann Résidence, Dakar',
    bloodGroup: 'AB+',
    medicalNotes: 'R.A.S',
    classId: 'c-1s1',
    className: '1ère S1',
    level: 'Première',
    academicYear: '2024-2025',
    status: 'INSCRIT',
    parentId: 'p-3',
    parentName: 'Khadija Fall',
    parentPhone: '+221 76 333 22 11',
    parentWhatsapp: '+221 76 333 22 11',
    relationship: 'Mère',
    totalFees: 420000,
    paidFees: 420000,
    feeBalance: 0,
    averageGrade: 16.8,
    unjustifiedAbsences: 0,
  },
  {
    id: 'stu-7',
    matricule: 'EIS-2024-0102',
    firstName: 'Aïssatou',
    lastName: 'Sarr',
    gender: 'FEMALE',
    birthDate: '2009-09-30',
    birthPlace: 'Dakar',
    nationality: 'Sénégalaise',
    photo: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=150&auto=format&fit=crop&q=80',
    address: 'Sacré-Cœur 3, Dakar',
    bloodGroup: 'O-',
    medicalNotes: 'Allergie arachide.',
    classId: 'c-3a',
    className: '3ème A',
    level: '3e',
    academicYear: '2024-2025',
    status: 'INSCRIT',
    parentId: 'p-4',
    parentName: 'Moustapha Sarr',
    parentPhone: '+221 77 222 66 55',
    parentWhatsapp: '+221 77 222 66 55',
    relationship: 'Père',
    totalFees: 350000,
    paidFees: 150000,
    feeBalance: 200000,
    averageGrade: 11.2,
    unjustifiedAbsences: 4,
  },
  {
    id: 'stu-8',
    matricule: 'EIS-2024-0103',
    firstName: 'Oumar',
    lastName: 'Sall',
    gender: 'MALE',
    birthDate: '2012-05-14',
    birthPlace: 'Saint-Louis',
    nationality: 'Sénégalaise',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    address: 'Ngor, Dakar',
    bloodGroup: 'A+',
    medicalNotes: 'R.A.S',
    classId: 'c-6a',
    className: '6ème A',
    level: '6e',
    academicYear: '2024-2025',
    status: 'INSCRIT',
    parentId: 'p-1',
    parentName: 'Mamadou Sall',
    parentPhone: '+221 77 333 44 55',
    parentWhatsapp: '+221 77 333 44 55',
    relationship: 'Père',
    totalFees: 320000,
    paidFees: 320000,
    feeBalance: 0,
    averageGrade: 15.6,
    unjustifiedAbsences: 0,
  },
  {
    id: 'stu-9',
    matricule: 'EIS-2024-0104',
    firstName: 'Mariama',
    lastName: 'Niane',
    gender: 'FEMALE',
    birthDate: '2012-10-19',
    birthPlace: 'Dakar',
    nationality: 'Sénégalaise',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    address: 'Ouakam, Dakar',
    bloodGroup: 'B+',
    medicalNotes: 'R.A.S',
    classId: 'c-6a',
    className: '6ème A',
    level: '6e',
    academicYear: '2024-2025',
    status: 'INSCRIT',
    parentId: 'p-2',
    parentName: 'Ibrahima Niane',
    parentPhone: '+221 76 111 22 33',
    parentWhatsapp: '+221 76 111 22 33',
    relationship: 'Père',
    totalFees: 320000,
    paidFees: 200000,
    feeBalance: 120000,
    averageGrade: 13.9,
    unjustifiedAbsences: 1,
  },
  {
    id: 'stu-10',
    matricule: 'EIS-2024-0105',
    firstName: 'Khady',
    lastName: 'Cissé',
    gender: 'FEMALE',
    birthDate: '2012-03-08',
    birthPlace: 'Dakar',
    nationality: 'Sénégalaise',
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    address: 'Yoff, Dakar',
    bloodGroup: 'O+',
    medicalNotes: 'R.A.S',
    classId: 'c-6b',
    className: '6ème B',
    level: '6e',
    academicYear: '2024-2025',
    status: 'INSCRIT',
    parentId: 'p-3',
    parentName: 'Alioune Cissé',
    parentPhone: '+221 70 888 77 66',
    parentWhatsapp: '+221 70 888 77 66',
    relationship: 'Père',
    totalFees: 320000,
    paidFees: 320000,
    feeBalance: 0,
    averageGrade: 16.1,
    unjustifiedAbsences: 0,
  },
  {
    id: 'stu-11',
    matricule: 'EIS-2024-0106',
    firstName: 'Alioune',
    lastName: 'Kane',
    gender: 'MALE',
    birthDate: '2011-07-25',
    birthPlace: 'Thiès',
    nationality: 'Sénégalaise',
    photo: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    address: 'Point E, Dakar',
    bloodGroup: 'AB+',
    medicalNotes: 'R.A.S',
    classId: 'c-5a',
    className: '5ème A',
    level: '5e',
    academicYear: '2024-2025',
    status: 'INSCRIT',
    parentId: 'p-4',
    parentName: 'Moussa Kane',
    parentPhone: '+221 77 444 33 22',
    parentWhatsapp: '+221 77 444 33 22',
    relationship: 'Père',
    totalFees: 330000,
    paidFees: 330000,
    feeBalance: 0,
    averageGrade: 14.5,
    unjustifiedAbsences: 0,
  },
  {
    id: 'stu-12',
    matricule: 'EIS-2024-0107',
    firstName: 'Ibrahima',
    lastName: 'Barry',
    gender: 'MALE',
    birthDate: '2008-12-04',
    birthPlace: 'Dakar',
    nationality: 'Sénégalaise',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    address: 'Fann Résidence, Dakar',
    bloodGroup: 'O+',
    medicalNotes: 'R.A.S',
    classId: 'c-2s',
    className: '2nde S',
    level: 'Seconde',
    academicYear: '2024-2025',
    status: 'INSCRIT',
    parentId: 'p-1',
    parentName: 'Amadou Barry',
    parentPhone: '+221 77 999 88 77',
    parentWhatsapp: '+221 77 999 88 77',
    relationship: 'Père',
    totalFees: 400000,
    paidFees: 250000,
    feeBalance: 150000,
    averageGrade: 15.3,
    unjustifiedAbsences: 1,
  },
  {
    id: 'stu-13',
    matricule: 'EIS-2024-0108',
    firstName: 'Korka',
    lastName: 'Diallo',
    gender: 'FEMALE',
    birthDate: '2007-04-18',
    birthPlace: 'Matam',
    nationality: 'Sénégalaise',
    photo: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    address: 'Sacré-Cœur, Dakar',
    bloodGroup: 'B+',
    medicalNotes: 'R.A.S',
    classId: 'c-tl2',
    className: 'Terminale L2',
    level: 'Terminale',
    academicYear: '2024-2025',
    status: 'INSCRIT',
    parentId: 'p-2',
    parentName: 'Boubacar Diallo',
    parentPhone: '+221 76 555 44 33',
    parentWhatsapp: '+221 76 555 44 33',
    relationship: 'Père',
    totalFees: 450000,
    paidFees: 450000,
    feeBalance: 0,
    averageGrade: 14.7,
    unjustifiedAbsences: 0,
  }
];

export const DEMO_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-001',
    receiptNumber: 'REC-2024-00431',
    transactionRef: 'WAV-SN-928174',
    studentId: 'stu-1',
    studentName: 'Awa Diop',
    matricule: 'EIS-2024-0012',
    className: '3ème A',
    parentName: 'Mamadou Diop',
    amount: 150000,
    method: 'WAVE',
    status: 'COMPLETED',
    feeType: 'Scolarité (Tranche 1)',
    paidAt: '2024-10-05 09:14',
    recordedBy: 'M. Sow (Comptable)',
    note: 'Paiement Wave instantané validé',
  },
  {
    id: 'pay-002',
    receiptNumber: 'REC-2024-00432',
    transactionRef: 'OM-SN-882190',
    studentId: 'stu-1',
    studentName: 'Awa Diop',
    matricule: 'EIS-2024-0012',
    className: '3ème A',
    parentName: 'Mamadou Diop',
    amount: 100000,
    method: 'ORANGE_MONEY',
    status: 'COMPLETED',
    feeType: 'Scolarité (Tranche 2)',
    paidAt: '2025-01-08 14:22',
    recordedBy: 'M. Sow (Comptable)',
    note: 'Paiement Orange Money direct',
  },
  {
    id: 'pay-003',
    receiptNumber: 'REC-2024-00433',
    transactionRef: 'CASH-0982',
    studentId: 'stu-3',
    studentName: 'Fatou Diop',
    matricule: 'EIS-2024-0014',
    className: 'CM2 A',
    parentName: 'Mamadou Diop',
    amount: 280000,
    method: 'CASH',
    status: 'COMPLETED',
    feeType: 'Scolarité Annuelle Totale',
    paidAt: '2024-09-25 11:30',
    recordedBy: 'M. Sow (Comptable)',
    note: 'Espèces remises à la caisse',
  },
  {
    id: 'pay-004',
    receiptNumber: 'REC-2024-00434',
    transactionRef: 'VIR-ECO-44910',
    studentId: 'stu-6',
    studentName: 'Babacar Fall',
    matricule: 'EIS-2024-0089',
    className: '1ère S1',
    parentName: 'Khadija Fall',
    amount: 420000,
    method: 'BANK_TRANSFER',
    status: 'COMPLETED',
    feeType: 'Scolarité & Uniforme',
    paidAt: '2024-09-28 16:45',
    recordedBy: 'M. Sow (Comptable)',
    note: 'Virement Ecobank validé par la banque',
  },
  {
    id: 'pay-005',
    receiptNumber: 'REC-2024-00435',
    transactionRef: 'WAV-SN-114892',
    studentId: 'stu-4',
    studentName: 'Cheikh Ndiaye',
    matricule: 'EIS-2024-0045',
    className: 'Terminale S2',
    parentName: 'Abdoulaye Ndiaye',
    amount: 300000,
    method: 'WAVE',
    status: 'COMPLETED',
    feeType: 'Scolarité (Tranches 1 & 2)',
    paidAt: '2024-10-12 10:05',
    recordedBy: 'M. Sow (Comptable)',
    note: 'Wave Mobile',
  }
];

export const DEMO_OVERDUE_FEES: StudentFee[] = [
  {
    id: 'fee-ov-1',
    studentId: 'stu-7',
    studentName: 'Aïssatou Sarr',
    matricule: 'EIS-2024-0102',
    className: '3ème A',
    parentName: 'Moustapha Sarr',
    parentPhone: '+221 77 222 66 55',
    feeType: 'Scolarité (Tranche 2 & 3)',
    totalAmount: 350000,
    paidAmount: 150000,
    dueAmount: 200000,
    dueDate: '2025-01-05',
    isOverdue: true,
    daysOverdue: 45,
    lastPaymentDate: '2024-10-02',
  },
  {
    id: 'fee-ov-2',
    studentId: 'stu-4',
    studentName: 'Cheikh Ndiaye',
    matricule: 'EIS-2024-0045',
    className: 'Terminale S2',
    parentName: 'Abdoulaye Ndiaye',
    parentPhone: '+221 78 444 88 99',
    feeType: 'Scolarité (Tranche 3)',
    totalAmount: 450000,
    paidAmount: 300000,
    dueAmount: 150000,
    dueDate: '2025-02-01',
    isOverdue: true,
    daysOverdue: 18,
    lastPaymentDate: '2024-10-12',
  },
  {
    id: 'fee-ov-3',
    studentId: 'stu-1',
    studentName: 'Awa Diop',
    matricule: 'EIS-2024-0012',
    className: '3ème A',
    parentName: 'Mamadou Diop',
    parentPhone: '+221 77 555 12 34',
    feeType: 'Scolarité (Tranche 3 - Solde)',
    totalAmount: 350000,
    paidAmount: 250000,
    dueAmount: 100000,
    dueDate: '2025-02-10',
    isOverdue: true,
    daysOverdue: 9,
    lastPaymentDate: '2025-01-08',
  },
  {
    id: 'fee-ov-4',
    studentId: 'stu-2',
    studentName: 'Moussa Diop',
    matricule: 'EIS-2024-0013',
    className: '6ème A',
    parentName: 'Mamadou Diop',
    parentPhone: '+221 77 555 12 34',
    feeType: 'Transport Scolaire (Janvier)',
    totalAmount: 50000,
    paidAmount: 0,
    dueAmount: 50000,
    dueDate: '2024-12-31',
    isOverdue: true,
    daysOverdue: 50,
  }
];

export const DEMO_REPORT_CARD_AWA: ReportCard = {
  studentId: 'stu-1',
  studentName: 'Awa Diop',
  matricule: 'EIS-2024-0012',
  className: '3ème A',
  academicYear: '2024-2025',
  term: 'TRIMESTRE_1',
  studentPhoto: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
  totalCoeff: 20.5,
  totalPoints: 336.2,
  generalAverage: 16.40,
  classAverage: 13.80,
  rank: 1,
  totalStudents: 29,
  absencesCount: 0,
  unjustifiedAbsencesCount: 0,
  appreciation: 'Trimestre remarquable ! Élève brillante, travailleuse et très attentive en classe. Félicitations du Conseil de Classe et Tableau d\'Honneur.',
  mention: 'Très Bien',
  subjects: [
    {
      subjectId: 's-math',
      subjectName: 'Mathématiques',
      coeff: 4.0,
      teacherName: 'M. Ibrahima Diallo',
      grades: [17, 18, 16.5],
      average: 17.17,
      classAverage: 12.8,
      minGrade: 6.5,
      maxGrade: 17.5,
      rank: 1,
      appreciation: 'Excellent niveau de raisonnement. Travail très rigoureux.',
    },
    {
      subjectId: 's-fr',
      subjectName: 'Français & Expression',
      coeff: 4.0,
      teacherName: 'Mme Fatou Bintou Sow',
      grades: [15, 16, 15.5],
      average: 15.50,
      classAverage: 13.4,
      minGrade: 8.0,
      maxGrade: 16.5,
      rank: 2,
      appreciation: 'Très bonne maîtrise de la langue et richesse de vocabulaire.',
    },
    {
      subjectId: 's-pc',
      subjectName: 'Physique - Chimie',
      coeff: 3.0,
      teacherName: 'M. Cheikh Tidiane Sy',
      grades: [18, 17.5, 17],
      average: 17.50,
      classAverage: 12.1,
      minGrade: 5.5,
      maxGrade: 18.0,
      rank: 1,
      appreciation: 'Excellente compréhension des lois physiques et démarche scientifique.',
    },
    {
      subjectId: 's-svt',
      subjectName: 'SVT',
      coeff: 2.0,
      teacherName: 'M. Ousmane Sembène',
      grades: [16, 17, 16.5],
      average: 16.50,
      classAverage: 13.6,
      minGrade: 9.0,
      maxGrade: 17.0,
      rank: 1,
      appreciation: 'Très bon esprit d\'analyse et schémas impeccables.',
    },
    {
      subjectId: 's-ang',
      subjectName: 'Anglais',
      coeff: 2.0,
      teacherName: 'Mme Mariama Ba',
      grades: [16.5, 17, 18],
      average: 17.17,
      classAverage: 14.2,
      minGrade: 8.5,
      maxGrade: 18.0,
      rank: 1,
      appreciation: 'Fluent and highly engaged. Keep up the excellent work!',
    },
    {
      subjectId: 's-hg',
      subjectName: 'Histoire - Géographie',
      coeff: 2.0,
      teacherName: 'M. Amadou Fall',
      grades: [15, 14.5, 16],
      average: 15.17,
      classAverage: 13.0,
      minGrade: 7.0,
      maxGrade: 16.5,
      rank: 2,
      appreciation: 'Bonne culture générale et synthèses claires.',
    },
    {
      subjectId: 's-eps',
      subjectName: 'Éducation Physique',
      coeff: 1.0,
      teacherName: 'M. Pape Diouf',
      grades: [15, 16],
      average: 15.50,
      classAverage: 14.8,
      minGrade: 10.0,
      maxGrade: 18.0,
      rank: 5,
      appreciation: 'Très bonne participation et esprit d\'équipe.',
    },
    {
      subjectId: 's-info',
      subjectName: 'Informatique',
      coeff: 1.5,
      teacherName: 'M. Moussa Niane',
      grades: [18, 19],
      average: 18.50,
      classAverage: 15.0,
      minGrade: 11.0,
      maxGrade: 19.5,
      rank: 1,
      appreciation: 'Très à l\'aise avec les concepts d\'algorithmique.',
    }
  ]
};

export const DEMO_ATTENDANCES: AttendanceRecord[] = [
  { id: 'att-1', studentId: 'stu-1', studentName: 'Awa Diop', matricule: 'EIS-2024-0012', classId: 'c-3a', className: '3ème A', date: '2025-02-19', status: 'PRESENT' },
  { id: 'att-2', studentId: 'stu-2', studentName: 'Moussa Diop', matricule: 'EIS-2024-0013', classId: 'c-6a', className: '6ème A', date: '2025-02-19', status: 'RETARD', lateMinutes: 15, reason: 'Embouteillages VDN' },
  { id: 'att-3', studentId: 'stu-3', studentName: 'Fatou Diop', matricule: 'EIS-2024-0014', classId: 'c-cm2', className: 'CM2 A', date: '2025-02-19', status: 'PRESENT' },
  { id: 'att-4', studentId: 'stu-4', studentName: 'Cheikh Ndiaye', matricule: 'EIS-2024-0045', classId: 'c-ts2', className: 'Terminale S2', date: '2025-02-19', status: 'ABSENT', reason: 'Non justifiée' },
  { id: 'att-5', studentId: 'stu-5', studentName: 'Seynabou Ndiaye', matricule: 'EIS-2024-0046', classId: 'c-4a', className: '4ème A', date: '2025-02-19', status: 'PRESENT' },
  { id: 'att-6', studentId: 'stu-6', studentName: 'Babacar Fall', matricule: 'EIS-2024-0089', classId: 'c-1s1', className: '1ère S1', date: '2025-02-19', status: 'PRESENT' },
  { id: 'att-7', studentId: 'stu-7', studentName: 'Aïssatou Sarr', matricule: 'EIS-2024-0102', classId: 'c-3a', className: '3ème A', date: '2025-02-19', status: 'JUSTIFIE', reason: 'Rendez-vous médical dentaire' },
];

export const DEMO_ALL_TIMETABLE_SLOTS: TimetableSlot[] = [
  // --- 3ème A ---
  { id: 'tt-3a-1', classId: 'c-3a', className: '3ème A', subjectId: 's-math', subjectName: 'Mathématiques', teacherId: 't-1', teacherName: 'M. Ibrahima Diallo', dayOfWeek: 'LUNDI', startTime: '08:00', endTime: '10:00', room: 'Salle 105', color: 'bg-blue-100 text-blue-900 border-blue-300' },
  { id: 'tt-3a-2', classId: 'c-3a', className: '3ème A', subjectId: 's-fr', subjectName: 'Français', teacherId: 't-2', teacherName: 'Mme Fatou Bintou Sow', dayOfWeek: 'LUNDI', startTime: '10:15', endTime: '12:15', room: 'Salle 105', color: 'bg-red-100 text-red-900 border-red-300' },
  { id: 'tt-3a-3', classId: 'c-3a', className: '3ème A', subjectId: 's-ang', subjectName: 'Anglais', teacherId: 't-4', teacherName: 'Mme Mariama Ba', dayOfWeek: 'LUNDI', startTime: '15:00', endTime: '17:00', room: 'Salle 105', color: 'bg-amber-100 text-amber-900 border-amber-300' },
  { id: 'tt-3a-4', classId: 'c-3a', className: '3ème A', subjectId: 's-pc', subjectName: 'Physique - Chimie', teacherId: 't-3', teacherName: 'M. Cheikh Tidiane Sy', dayOfWeek: 'MARDI', startTime: '08:00', endTime: '10:00', room: 'Labo Sciences 2', color: 'bg-purple-100 text-purple-900 border-purple-300' },
  { id: 'tt-3a-5', classId: 'c-3a', className: '3ème A', subjectId: 's-svt', subjectName: 'SVT', teacherId: 't-5', teacherName: 'M. Ousmane Sembène', dayOfWeek: 'MARDI', startTime: '10:15', endTime: '12:15', room: 'Labo Sciences 1', color: 'bg-emerald-100 text-emerald-900 border-emerald-300' },
  { id: 'tt-3a-6', classId: 'c-3a', className: '3ème A', subjectId: 's-hg', subjectName: 'Histoire - Géo', teacherId: 't-7', teacherName: 'M. Amadou Fall', dayOfWeek: 'MERCREDI', startTime: '08:00', endTime: '10:00', room: 'Salle 105', color: 'bg-orange-100 text-orange-900 border-orange-300' },
  { id: 'tt-3a-7', classId: 'c-3a', className: '3ème A', subjectId: 's-eps', subjectName: 'EPS (Sport)', teacherId: 't-8', teacherName: 'M. Pape Diouf', dayOfWeek: 'MERCREDI', startTime: '10:15', endTime: '12:15', room: 'Terrain Omnisports', color: 'bg-cyan-100 text-cyan-900 border-cyan-300' },
  { id: 'tt-3a-8', classId: 'c-3a', className: '3ème A', subjectId: 's-math', subjectName: 'Mathématiques', teacherId: 't-1', teacherName: 'M. Ibrahima Diallo', dayOfWeek: 'JEUDI', startTime: '08:00', endTime: '10:00', room: 'Salle 105', color: 'bg-blue-100 text-blue-900 border-blue-300' },
  { id: 'tt-3a-9', classId: 'c-3a', className: '3ème A', subjectId: 's-info', subjectName: 'Informatique', teacherId: 't-9', teacherName: 'M. Moussa Niane', dayOfWeek: 'JEUDI', startTime: '10:15', endTime: '12:15', room: 'Salle Info B', color: 'bg-sky-100 text-sky-900 border-sky-300' },
  { id: 'tt-3a-10', classId: 'c-3a', className: '3ème A', subjectId: 's-fr', subjectName: 'Français', teacherId: 't-2', teacherName: 'Mme Fatou Bintou Sow', dayOfWeek: 'VENDREDI', startTime: '08:00', endTime: '10:00', room: 'Salle 105', color: 'bg-red-100 text-red-900 border-red-300' },
  { id: 'tt-3a-11', classId: 'c-3a', className: '3ème A', subjectId: 's-ang', subjectName: 'Anglais', teacherId: 't-4', teacherName: 'Mme Mariama Ba', dayOfWeek: 'VENDREDI', startTime: '10:15', endTime: '12:15', room: 'Salle 105', color: 'bg-amber-100 text-amber-900 border-amber-300' },

  // --- 6ème A ---
  { id: 'tt-6a-1', classId: 'c-6a', className: '6ème A', subjectId: 's-fr', subjectName: 'Français', teacherId: 't-2', teacherName: 'Mme Fatou Bintou Sow', dayOfWeek: 'LUNDI', startTime: '08:00', endTime: '10:00', room: 'Salle 101', color: 'bg-red-100 text-red-900 border-red-300' },
  { id: 'tt-6a-2', classId: 'c-6a', className: '6ème A', subjectId: 's-math', subjectName: 'Mathématiques', teacherId: 't-1', teacherName: 'M. Ibrahima Diallo', dayOfWeek: 'LUNDI', startTime: '10:15', endTime: '12:15', room: 'Salle 101', color: 'bg-blue-100 text-blue-900 border-blue-300' },
  { id: 'tt-6a-3', classId: 'c-6a', className: '6ème A', subjectId: 's-ang', subjectName: 'Anglais', teacherId: 't-4', teacherName: 'Mme Mariama Ba', dayOfWeek: 'MARDI', startTime: '08:00', endTime: '10:00', room: 'Salle 101', color: 'bg-amber-100 text-amber-900 border-amber-300' },
  { id: 'tt-6a-4', classId: 'c-6a', className: '6ème A', subjectId: 's-svt', subjectName: 'SVT', teacherId: 't-5', teacherName: 'M. Ousmane Sembène', dayOfWeek: 'MARDI', startTime: '10:15', endTime: '12:15', room: 'Labo Sciences 1', color: 'bg-emerald-100 text-emerald-900 border-emerald-300' },
  { id: 'tt-6a-5', classId: 'c-6a', className: '6ème A', subjectId: 's-hg', subjectName: 'Histoire - Géo', teacherId: 't-7', teacherName: 'M. Amadou Fall', dayOfWeek: 'MERCREDI', startTime: '08:00', endTime: '10:00', room: 'Salle 101', color: 'bg-orange-100 text-orange-900 border-orange-300' },
  { id: 'tt-6a-6', classId: 'c-6a', className: '6ème A', subjectId: 's-eps', subjectName: 'EPS (Sport)', teacherId: 't-8', teacherName: 'M. Pape Diouf', dayOfWeek: 'MERCREDI', startTime: '10:15', endTime: '12:15', room: 'Terrain Omnisports', color: 'bg-cyan-100 text-cyan-900 border-cyan-300' },
  { id: 'tt-6a-7', classId: 'c-6a', className: '6ème A', subjectId: 's-fr', subjectName: 'Français', teacherId: 't-2', teacherName: 'Mme Fatou Bintou Sow', dayOfWeek: 'JEUDI', startTime: '08:00', endTime: '10:00', room: 'Salle 101', color: 'bg-red-100 text-red-900 border-red-300' },
  { id: 'tt-6a-8', classId: 'c-6a', className: '6ème A', subjectId: 's-math', subjectName: 'Mathématiques', teacherId: 't-1', teacherName: 'M. Ibrahima Diallo', dayOfWeek: 'JEUDI', startTime: '10:15', endTime: '12:15', room: 'Salle 101', color: 'bg-blue-100 text-blue-900 border-blue-300' },
  { id: 'tt-6a-9', classId: 'c-6a', className: '6ème A', subjectId: 's-info', subjectName: 'Informatique', teacherId: 't-9', teacherName: 'M. Moussa Niane', dayOfWeek: 'VENDREDI', startTime: '08:00', endTime: '10:00', room: 'Salle Info A', color: 'bg-sky-100 text-sky-900 border-sky-300' },
  { id: 'tt-6a-10', classId: 'c-6a', className: '6ème A', subjectId: 's-ang', subjectName: 'Anglais', teacherId: 't-4', teacherName: 'Mme Mariama Ba', dayOfWeek: 'VENDREDI', startTime: '10:15', endTime: '12:15', room: 'Salle 101', color: 'bg-amber-100 text-amber-900 border-amber-300' },

  // --- 6ème B ---
  { id: 'tt-6b-1', classId: 'c-6b', className: '6ème B', subjectId: 's-math', subjectName: 'Mathématiques', teacherId: 't-1', teacherName: 'M. Ibrahima Diallo', dayOfWeek: 'LUNDI', startTime: '08:00', endTime: '10:00', room: 'Salle 102', color: 'bg-blue-100 text-blue-900 border-blue-300' },
  { id: 'tt-6b-2', classId: 'c-6b', className: '6ème B', subjectId: 's-fr', subjectName: 'Français', teacherId: 't-2', teacherName: 'Mme Fatou Bintou Sow', dayOfWeek: 'LUNDI', startTime: '10:15', endTime: '12:15', room: 'Salle 102', color: 'bg-red-100 text-red-900 border-red-300' },
  { id: 'tt-6b-3', classId: 'c-6b', className: '6ème B', subjectId: 's-svt', subjectName: 'SVT', teacherId: 't-5', teacherName: 'M. Ousmane Sembène', dayOfWeek: 'MARDI', startTime: '08:00', endTime: '10:00', room: 'Labo Sciences 1', color: 'bg-emerald-100 text-emerald-900 border-emerald-300' },
  { id: 'tt-6b-4', classId: 'c-6b', className: '6ème B', subjectId: 's-ang', subjectName: 'Anglais', teacherId: 't-4', teacherName: 'Mme Mariama Ba', dayOfWeek: 'MARDI', startTime: '10:15', endTime: '12:15', room: 'Salle 102', color: 'bg-amber-100 text-amber-900 border-amber-300' },
  { id: 'tt-6b-5', classId: 'c-6b', className: '6ème B', subjectId: 's-eps', subjectName: 'EPS (Sport)', teacherId: 't-8', teacherName: 'M. Pape Diouf', dayOfWeek: 'MERCREDI', startTime: '08:00', endTime: '10:00', room: 'Terrain Omnisports', color: 'bg-cyan-100 text-cyan-900 border-cyan-300' },
  { id: 'tt-6b-6', classId: 'c-6b', className: '6ème B', subjectId: 's-hg', subjectName: 'Histoire - Géo', teacherId: 't-7', teacherName: 'M. Amadou Fall', dayOfWeek: 'MERCREDI', startTime: '10:15', endTime: '12:15', room: 'Salle 102', color: 'bg-orange-100 text-orange-900 border-orange-300' },
  { id: 'tt-6b-7', classId: 'c-6b', className: '6ème B', subjectId: 's-math', subjectName: 'Mathématiques', teacherId: 't-1', teacherName: 'M. Ibrahima Diallo', dayOfWeek: 'JEUDI', startTime: '08:00', endTime: '10:00', room: 'Salle 102', color: 'bg-blue-100 text-blue-900 border-blue-300' },
  { id: 'tt-6b-8', classId: 'c-6b', className: '6ème B', subjectId: 's-fr', subjectName: 'Français', teacherId: 't-2', teacherName: 'Mme Fatou Bintou Sow', dayOfWeek: 'JEUDI', startTime: '10:15', endTime: '12:15', room: 'Salle 102', color: 'bg-red-100 text-red-900 border-red-300' },
  { id: 'tt-6b-9', classId: 'c-6b', className: '6ème B', subjectId: 's-ang', subjectName: 'Anglais', teacherId: 't-4', teacherName: 'Mme Mariama Ba', dayOfWeek: 'VENDREDI', startTime: '08:00', endTime: '10:00', room: 'Salle 102', color: 'bg-amber-100 text-amber-900 border-amber-300' },
  { id: 'tt-6b-10', classId: 'c-6b', className: '6ème B', subjectId: 's-info', subjectName: 'Informatique', teacherId: 't-9', teacherName: 'M. Moussa Niane', dayOfWeek: 'VENDREDI', startTime: '10:15', endTime: '12:15', room: 'Salle Info A', color: 'bg-sky-100 text-sky-900 border-sky-300' },

  // --- 5ème A ---
  { id: 'tt-5a-1', classId: 'c-5a', className: '5ème A', subjectId: 's-pc', subjectName: 'Physique - Chimie', teacherId: 't-3', teacherName: 'M. Cheikh Tidiane Sy', dayOfWeek: 'LUNDI', startTime: '08:00', endTime: '10:00', room: 'Labo Sciences 2', color: 'bg-purple-100 text-purple-900 border-purple-300' },
  { id: 'tt-5a-2', classId: 'c-5a', className: '5ème A', subjectId: 's-fr', subjectName: 'Français', teacherId: 't-2', teacherName: 'Mme Fatou Bintou Sow', dayOfWeek: 'LUNDI', startTime: '10:15', endTime: '12:15', room: 'Salle 103', color: 'bg-red-100 text-red-900 border-red-300' },
  { id: 'tt-5a-3', classId: 'c-5a', className: '5ème A', subjectId: 's-math', subjectName: 'Mathématiques', teacherId: 't-1', teacherName: 'M. Ibrahima Diallo', dayOfWeek: 'MARDI', startTime: '08:00', endTime: '10:00', room: 'Salle 103', color: 'bg-blue-100 text-blue-900 border-blue-300' },
  { id: 'tt-5a-4', classId: 'c-5a', className: '5ème A', subjectId: 's-svt', subjectName: 'SVT', teacherId: 't-5', teacherName: 'M. Ousmane Sembène', dayOfWeek: 'MARDI', startTime: '10:15', endTime: '12:15', room: 'Labo Sciences 1', color: 'bg-emerald-100 text-emerald-900 border-emerald-300' },
  { id: 'tt-5a-5', classId: 'c-5a', className: '5ème A', subjectId: 's-ang', subjectName: 'Anglais', teacherId: 't-4', teacherName: 'Mme Mariama Ba', dayOfWeek: 'MERCREDI', startTime: '08:00', endTime: '10:00', room: 'Salle 103', color: 'bg-amber-100 text-amber-900 border-amber-300' },
  { id: 'tt-5a-6', classId: 'c-5a', className: '5ème A', subjectId: 's-eps', subjectName: 'EPS (Sport)', teacherId: 't-8', teacherName: 'M. Pape Diouf', dayOfWeek: 'MERCREDI', startTime: '10:15', endTime: '12:15', room: 'Terrain Omnisports', color: 'bg-cyan-100 text-cyan-900 border-cyan-300' },
  { id: 'tt-5a-7', classId: 'c-5a', className: '5ème A', subjectId: 's-pc', subjectName: 'Physique - Chimie', teacherId: 't-3', teacherName: 'M. Cheikh Tidiane Sy', dayOfWeek: 'JEUDI', startTime: '08:00', endTime: '10:00', room: 'Labo Sciences 2', color: 'bg-purple-100 text-purple-900 border-purple-300' },
  { id: 'tt-5a-8', classId: 'c-5a', className: '5ème A', subjectId: 's-fr', subjectName: 'Français', teacherId: 't-2', teacherName: 'Mme Fatou Bintou Sow', dayOfWeek: 'JEUDI', startTime: '10:15', endTime: '12:15', room: 'Salle 103', color: 'bg-red-100 text-red-900 border-red-300' },
  { id: 'tt-5a-9', classId: 'c-5a', className: '5ème A', subjectId: 's-math', subjectName: 'Mathématiques', teacherId: 't-1', teacherName: 'M. Ibrahima Diallo', dayOfWeek: 'VENDREDI', startTime: '08:00', endTime: '10:00', room: 'Salle 103', color: 'bg-blue-100 text-blue-900 border-blue-300' },
  { id: 'tt-5a-10', classId: 'c-5a', className: '5ème A', subjectId: 's-hg', subjectName: 'Histoire - Géo', teacherId: 't-7', teacherName: 'M. Amadou Fall', dayOfWeek: 'VENDREDI', startTime: '10:15', endTime: '12:15', room: 'Salle 103', color: 'bg-orange-100 text-orange-900 border-orange-300' },

  // --- 4ème A ---
  { id: 'tt-4a-1', classId: 'c-4a', className: '4ème A', subjectId: 's-ang', subjectName: 'Anglais', teacherId: 't-4', teacherName: 'Mme Mariama Ba', dayOfWeek: 'LUNDI', startTime: '08:00', endTime: '10:00', room: 'Salle 104', color: 'bg-amber-100 text-amber-900 border-amber-300' },
  { id: 'tt-4a-2', classId: 'c-4a', className: '4ème A', subjectId: 's-math', subjectName: 'Mathématiques', teacherId: 't-1', teacherName: 'M. Ibrahima Diallo', dayOfWeek: 'LUNDI', startTime: '10:15', endTime: '12:15', room: 'Salle 104', color: 'bg-blue-100 text-blue-900 border-blue-300' },
  { id: 'tt-4a-3', classId: 'c-4a', className: '4ème A', subjectId: 's-fr', subjectName: 'Français', teacherId: 't-2', teacherName: 'Mme Fatou Bintou Sow', dayOfWeek: 'MARDI', startTime: '08:00', endTime: '10:00', room: 'Salle 104', color: 'bg-red-100 text-red-900 border-red-300' },
  { id: 'tt-4a-4', classId: 'c-4a', className: '4ème A', subjectId: 's-pc', subjectName: 'Physique - Chimie', teacherId: 't-3', teacherName: 'M. Cheikh Tidiane Sy', dayOfWeek: 'MARDI', startTime: '10:15', endTime: '12:15', room: 'Labo Sciences 2', color: 'bg-purple-100 text-purple-900 border-purple-300' },
  { id: 'tt-4a-5', classId: 'c-4a', className: '4ème A', subjectId: 's-svt', subjectName: 'SVT', teacherId: 't-5', teacherName: 'M. Ousmane Sembène', dayOfWeek: 'MERCREDI', startTime: '08:00', endTime: '10:00', room: 'Labo Sciences 1', color: 'bg-emerald-100 text-emerald-900 border-emerald-300' },
  { id: 'tt-4a-6', classId: 'c-4a', className: '4ème A', subjectId: 's-eps', subjectName: 'EPS (Sport)', teacherId: 't-8', teacherName: 'M. Pape Diouf', dayOfWeek: 'MERCREDI', startTime: '10:15', endTime: '12:15', room: 'Terrain Omnisports', color: 'bg-cyan-100 text-cyan-900 border-cyan-300' },
  { id: 'tt-4a-7', classId: 'c-4a', className: '4ème A', subjectId: 's-ang', subjectName: 'Anglais', teacherId: 't-4', teacherName: 'Mme Mariama Ba', dayOfWeek: 'JEUDI', startTime: '08:00', endTime: '10:00', room: 'Salle 104', color: 'bg-amber-100 text-amber-900 border-amber-300' },
  { id: 'tt-4a-8', classId: 'c-4a', className: '4ème A', subjectId: 's-math', subjectName: 'Mathématiques', teacherId: 't-1', teacherName: 'M. Ibrahima Diallo', dayOfWeek: 'JEUDI', startTime: '10:15', endTime: '12:15', room: 'Salle 104', color: 'bg-blue-100 text-blue-900 border-blue-300' },
  { id: 'tt-4a-9', classId: 'c-4a', className: '4ème A', subjectId: 's-hg', subjectName: 'Histoire - Géo', teacherId: 't-7', teacherName: 'M. Amadou Fall', dayOfWeek: 'VENDREDI', startTime: '08:00', endTime: '10:00', room: 'Salle 104', color: 'bg-orange-100 text-orange-900 border-orange-300' },
  { id: 'tt-4a-10', classId: 'c-4a', className: '4ème A', subjectId: 's-fr', subjectName: 'Français', teacherId: 't-2', teacherName: 'Mme Fatou Bintou Sow', dayOfWeek: 'VENDREDI', startTime: '10:15', endTime: '12:15', room: 'Salle 104', color: 'bg-red-100 text-red-900 border-red-300' },

  // --- Terminale S2 ---
  { id: 'tt-ts2-1', classId: 'c-ts2', className: 'Terminale S2', subjectId: 's-math', subjectName: 'Mathématiques', teacherId: 't-1', teacherName: 'M. Ibrahima Diallo', dayOfWeek: 'LUNDI', startTime: '08:00', endTime: '10:00', room: 'Salle 203', color: 'bg-blue-100 text-blue-900 border-blue-300' },
  { id: 'tt-ts2-2', classId: 'c-ts2', className: 'Terminale S2', subjectId: 's-pc', subjectName: 'Physique - Chimie', teacherId: 't-3', teacherName: 'M. Cheikh Tidiane Sy', dayOfWeek: 'LUNDI', startTime: '10:15', endTime: '12:15', room: 'Labo Sciences 2', color: 'bg-purple-100 text-purple-900 border-purple-300' },
  { id: 'tt-ts2-3', classId: 'c-ts2', className: 'Terminale S2', subjectId: 's-svt', subjectName: 'SVT', teacherId: 't-5', teacherName: 'M. Ousmane Sembène', dayOfWeek: 'MARDI', startTime: '08:00', endTime: '10:00', room: 'Labo Sciences 1', color: 'bg-emerald-100 text-emerald-900 border-emerald-300' },
  { id: 'tt-ts2-4', classId: 'c-ts2', className: 'Terminale S2', subjectId: 's-philo', subjectName: 'Philosophie', teacherId: 't-10', teacherName: 'Mme Khady Gomis', dayOfWeek: 'MARDI', startTime: '10:15', endTime: '12:15', room: 'Salle 203', color: 'bg-indigo-100 text-indigo-900 border-indigo-300' },
  { id: 'tt-ts2-5', classId: 'c-ts2', className: 'Terminale S2', subjectId: 's-ang', subjectName: 'Anglais', teacherId: 't-4', teacherName: 'Mme Mariama Ba', dayOfWeek: 'MERCREDI', startTime: '08:00', endTime: '10:00', room: 'Salle 203', color: 'bg-amber-100 text-amber-900 border-amber-300' },
  { id: 'tt-ts2-6', classId: 'c-ts2', className: 'Terminale S2', subjectId: 's-eps', subjectName: 'EPS (Sport)', teacherId: 't-8', teacherName: 'M. Pape Diouf', dayOfWeek: 'MERCREDI', startTime: '10:15', endTime: '12:15', room: 'Terrain Omnisports', color: 'bg-cyan-100 text-cyan-900 border-cyan-300' },
  { id: 'tt-ts2-7', classId: 'c-ts2', className: 'Terminale S2', subjectId: 's-math', subjectName: 'Mathématiques', teacherId: 't-1', teacherName: 'M. Ibrahima Diallo', dayOfWeek: 'JEUDI', startTime: '08:00', endTime: '10:00', room: 'Salle 203', color: 'bg-blue-100 text-blue-900 border-blue-300' },
  { id: 'tt-ts2-8', classId: 'c-ts2', className: 'Terminale S2', subjectId: 's-pc', subjectName: 'Physique - Chimie', teacherId: 't-3', teacherName: 'M. Cheikh Tidiane Sy', dayOfWeek: 'JEUDI', startTime: '10:15', endTime: '12:15', room: 'Labo Sciences 2', color: 'bg-purple-100 text-purple-900 border-purple-300' },
  { id: 'tt-ts2-9', classId: 'c-ts2', className: 'Terminale S2', subjectId: 's-svt', subjectName: 'SVT', teacherId: 't-5', teacherName: 'M. Ousmane Sembène', dayOfWeek: 'VENDREDI', startTime: '08:00', endTime: '10:00', room: 'Labo Sciences 1', color: 'bg-emerald-100 text-emerald-900 border-emerald-300' },
  { id: 'tt-ts2-10', classId: 'c-ts2', className: 'Terminale S2', subjectId: 's-hg', subjectName: 'Histoire - Géo', teacherId: 't-7', teacherName: 'M. Amadou Fall', dayOfWeek: 'VENDREDI', startTime: '10:15', endTime: '12:15', room: 'Salle 203', color: 'bg-orange-100 text-orange-900 border-orange-300' },

  // --- CM2 A ---
  { id: 'tt-cm2-1', classId: 'c-cm2', className: 'CM2 A', subjectId: 's-fr', subjectName: 'Français & Grammaire', teacherId: 't-6', teacherName: 'Mme Aminata Traoré', dayOfWeek: 'LUNDI', startTime: '08:00', endTime: '10:00', room: 'Salle P06', color: 'bg-red-100 text-red-900 border-red-300' },
  { id: 'tt-cm2-2', classId: 'c-cm2', className: 'CM2 A', subjectId: 's-math', subjectName: 'Calcul & Géométrie', teacherId: 't-6', teacherName: 'Mme Aminata Traoré', dayOfWeek: 'LUNDI', startTime: '10:15', endTime: '12:15', room: 'Salle P06', color: 'bg-blue-100 text-blue-900 border-blue-300' },
  { id: 'tt-cm2-3', classId: 'c-cm2', className: 'CM2 A', subjectId: 's-hg', subjectName: 'Histoire - Géo & Éveil', teacherId: 't-6', teacherName: 'Mme Aminata Traoré', dayOfWeek: 'MARDI', startTime: '08:00', endTime: '10:00', room: 'Salle P06', color: 'bg-orange-100 text-orange-900 border-orange-300' },
  { id: 'tt-cm2-4', classId: 'c-cm2', className: 'CM2 A', subjectId: 's-svt', subjectName: 'Sciences & Observation', teacherId: 't-6', teacherName: 'Mme Aminata Traoré', dayOfWeek: 'MARDI', startTime: '10:15', endTime: '12:15', room: 'Salle P06', color: 'bg-emerald-100 text-emerald-900 border-emerald-300' },
  { id: 'tt-cm2-5', classId: 'c-cm2', className: 'CM2 A', subjectId: 's-ang', subjectName: 'Initiation Anglais', teacherId: 't-4', teacherName: 'Mme Mariama Ba', dayOfWeek: 'MERCREDI', startTime: '08:00', endTime: '10:00', room: 'Salle P06', color: 'bg-amber-100 text-amber-900 border-amber-300' },
  { id: 'tt-cm2-6', classId: 'c-cm2', className: 'CM2 A', subjectId: 's-eps', subjectName: 'Éducation Physique', teacherId: 't-8', teacherName: 'M. Pape Diouf', dayOfWeek: 'MERCREDI', startTime: '10:15', endTime: '12:15', room: 'Cour Primaire', color: 'bg-cyan-100 text-cyan-900 border-cyan-300' },
  { id: 'tt-cm2-7', classId: 'c-cm2', className: 'CM2 A', subjectId: 's-fr', subjectName: 'Lecture & Vocabulaire', teacherId: 't-6', teacherName: 'Mme Aminata Traoré', dayOfWeek: 'JEUDI', startTime: '08:00', endTime: '10:00', room: 'Salle P06', color: 'bg-red-100 text-red-900 border-red-300' },
  { id: 'tt-cm2-8', classId: 'c-cm2', className: 'CM2 A', subjectId: 's-math', subjectName: 'Problèmes & Opérations', teacherId: 't-6', teacherName: 'Mme Aminata Traoré', dayOfWeek: 'JEUDI', startTime: '10:15', endTime: '12:15', room: 'Salle P06', color: 'bg-blue-100 text-blue-900 border-blue-300' },
  { id: 'tt-cm2-9', classId: 'c-cm2', className: 'CM2 A', subjectId: 's-info', subjectName: 'Initiation Informatique', teacherId: 't-9', teacherName: 'M. Moussa Niane', dayOfWeek: 'VENDREDI', startTime: '08:00', endTime: '10:00', room: 'Salle Info A', color: 'bg-sky-100 text-sky-900 border-sky-300' },
  { id: 'tt-cm2-10', classId: 'c-cm2', className: 'CM2 A', subjectId: 's-fr', subjectName: 'Dictée & Rédaction', teacherId: 't-6', teacherName: 'Mme Aminata Traoré', dayOfWeek: 'VENDREDI', startTime: '10:15', endTime: '12:15', room: 'Salle P06', color: 'bg-red-100 text-red-900 border-red-300' },
];

export const DEMO_TIMETABLE_3A: TimetableSlot[] = DEMO_ALL_TIMETABLE_SLOTS.filter(s => s.classId === 'c-3a');

export const DEMO_HOMEWORK: HomeworkItem[] = [
  {
    id: 'hw-1',
    classId: 'c-3a',
    className: '3ème A',
    subjectId: 's-math',
    subjectName: 'Mathématiques',
    teacherName: 'M. Ibrahima Diallo',
    title: 'Exercices Théorème de Thalès et Trigonométrie',
    description: 'Faire les exercices 14, 15 et 18 page 92 du manuel CIAM 3ème. Justifier soigneusement chaque étape géométrique.',
    assignedDate: '2025-02-18',
    dueDate: '2025-02-23',
    submissionsCount: 22,
    totalStudents: 29,
  },
  {
    id: 'hw-2',
    classId: 'c-3a',
    className: '3ème A',
    subjectId: 's-fr',
    subjectName: 'Français',
    teacherName: 'Mme Fatou Bintou Sow',
    title: 'Dissertation littéraire sur "Une Si Longue Lettre"',
    description: 'Rédiger une introduction et un plan détaillé sur la condition féminine selon Mariama Bâ.',
    assignedDate: '2025-02-17',
    dueDate: '2025-02-24',
    submissionsCount: 19,
    totalStudents: 29,
  },
  {
    id: 'hw-3',
    classId: 'c-3a',
    className: '3ème A',
    subjectId: 's-pc',
    subjectName: 'Physique - Chimie',
    teacherName: 'M. Cheikh Tidiane Sy',
    title: 'Compte rendu de TP : Oxydoréduction & Solutions ioniques',
    description: 'Compléter le tableau de mesures et calculer les concentrations molaires.',
    assignedDate: '2025-02-19',
    dueDate: '2025-02-26',
    submissionsCount: 12,
    totalStudents: 29,
  }
];

export const DEMO_PROMOTIONS: PromotionRecord[] = [
  {
    id: 'prom-1',
    studentId: 'stu-1',
    studentName: 'Awa Diop',
    matricule: 'EIS-2024-0012',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    currentClassId: 'c-3a',
    currentClassName: '3ème A',
    annualAverage: 16.4,
    status: 'ADMIS',
    nextClassName: '2nde Scientifique (2nde S)',
    mention: 'FELICITATIONS',
    councilObservation: 'Excellents résultats annuels et discipline exemplaire. Admise en 2nde S avec les Félicitations unanimes du conseil des professeurs.',
    deliberationDate: '2025-06-28',
    isPublishedToParents: true,
  },
  {
    id: 'prom-2',
    studentId: 'stu-2',
    studentName: 'Moussa Diop',
    matricule: 'EIS-2024-0013',
    photo: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    currentClassId: 'c-6a',
    currentClassName: '6ème A',
    annualAverage: 14.8,
    status: 'ADMIS',
    nextClassName: '5ème A',
    mention: 'TABLEAU_HONNEUR',
    councilObservation: 'Bon travail tout au long de l\'année. Progression continue en mathématiques et français. Admis en 5ème A.',
    deliberationDate: '2025-06-28',
    isPublishedToParents: true,
  },
  {
    id: 'prom-3',
    studentId: 'stu-3',
    studentName: 'Fatou Diop',
    matricule: 'EIS-2024-0014',
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    currentClassId: 'c-cm2',
    currentClassName: 'CM2 A',
    annualAverage: 17.2,
    status: 'ADMIS',
    nextClassName: '6ème A (Collège)',
    mention: 'FELICITATIONS',
    councilObservation: 'Major de promotion du cycle élémentaire. Succès brillant à l\'examen du CFEE et de l\'Entrée en 6ème. Admise au Collège.',
    deliberationDate: '2025-06-28',
    isPublishedToParents: true,
  },
  {
    id: 'prom-4',
    studentId: 'stu-4',
    studentName: 'Cheikh Ndiaye',
    matricule: 'EIS-2024-0045',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    currentClassId: 'c-ts2',
    currentClassName: 'Terminale S2',
    annualAverage: 15.5,
    status: 'ADMIS',
    nextClassName: 'Baccalauréat Scientifique (Admis avec Mention)',
    mention: 'TABLEAU_HONNEUR',
    councilObservation: 'Avis Très Favorable pour le Baccalauréat Scientifique S2. Admis pour les classes préparatoires et études supérieures.',
    deliberationDate: '2025-06-28',
    isPublishedToParents: true,
  },
  {
    id: 'prom-5',
    studentId: 'stu-5',
    studentName: 'Seynabou Ndiaye',
    matricule: 'EIS-2024-0046',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    currentClassId: 'c-4a',
    currentClassName: '4ème A',
    annualAverage: 13.9,
    status: 'ADMIS',
    nextClassName: '3ème A',
    mention: 'ENCOURAGEMENTS',
    councilObservation: 'Travail sérieux et régulier. Admise en classe de 3ème.',
    deliberationDate: '2025-06-28',
    isPublishedToParents: true,
  },
  {
    id: 'prom-6',
    studentId: 'stu-6',
    studentName: 'Babacar Fall',
    matricule: 'EIS-2024-0089',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    currentClassId: 'c-1s1',
    currentClassName: '1ère S1',
    annualAverage: 16.8,
    status: 'ADMIS',
    nextClassName: 'Terminale S1',
    mention: 'FELICITATIONS',
    councilObservation: 'Excellente maîtrise en sciences exactes. Admis en Terminale S1 avec Félicitations.',
    deliberationDate: '2025-06-28',
    isPublishedToParents: true,
  },
  {
    id: 'prom-7',
    studentId: 'stu-7',
    studentName: 'Aïssatou Sarr',
    matricule: 'EIS-2024-0102',
    photo: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=150&auto=format&fit=crop&q=80',
    currentClassId: 'c-3a',
    currentClassName: '3ème A',
    annualAverage: 9.4,
    status: 'REDOUBLE',
    nextClassName: 'Maintien en 3ème A (Redoublement)',
    mention: 'AVERTISSEMENT',
    councilObservation: 'Moyenne insuffisante pour le passage en 2nde. Le conseil autorise le redoublement en 3ème pour consolidation.',
    deliberationDate: '2025-06-28',
    isPublishedToParents: true,
  }
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Paiement Wave Reçu',
    message: 'Le versement de 150 000 FCFA pour Awa Diop a été validé avec succès (Ref: WAV-SN-928174).',
    type: 'PAYMENT_RECEIVED',
    channel: 'WHATSAPP',
    createdAt: 'Il y a 10 minutes',
    isRead: false,
    recipient: 'M. Mamadou Diop'
  },
  {
    id: 'notif-2',
    title: 'Alerte Retard / Absence',
    message: 'Moussa Diop a été enregistré en retard de 15 minutes en 6ème A ce matin.',
    type: 'STUDENT_ABSENT',
    channel: 'SMS',
    createdAt: 'Il y a 45 minutes',
    isRead: false,
    recipient: 'M. Mamadou Diop'
  },
  {
    id: 'notif-3',
    title: 'Bulletin du 1er Trimestre Disponible',
    message: 'Le bulletin officiel de Awa Diop (Moyenne : 16.40/20 - Rang : 1ère) est consultable et téléchargeable.',
    type: 'REPORT_AVAILABLE',
    channel: 'IN_APP',
    createdAt: 'Il y a 2 heures',
    isRead: true,
    recipient: 'Espace Parents'
  },
  {
    id: 'notif-4',
    title: 'Rappel Échéance de Scolarité',
    message: 'La 3ème tranche de scolarité de 100 000 FCFA pour Awa Diop arrive à échéance le 28 février.',
    type: 'PAYMENT_DUE',
    channel: 'WHATSAPP',
    createdAt: 'Il y a 1 jour',
    isRead: true,
    recipient: 'M. Mamadou Diop'
  },
  {
    id: 'notif-5',
    title: 'Résultats des Délibérations de Fin d\'Année',
    message: 'Les décisions de passage en classe supérieure pour l\'année 2025-2026 sont consultables.',
    type: 'ANNOUNCEMENT',
    channel: 'IN_APP',
    createdAt: 'Il y a 3 heures',
    isRead: false,
    recipient: 'Tous les Parents'
  }
];
